version: "3.4"

services:
  carla:
    image: ${CARLA_REPO}:${CARLA_TAG} # see adore_if_carla.mk to assign this value 
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    command: /bin/bash ./CarlaUE4.sh -RenderOffScreen
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  carla-ros-bridge:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ros-bridge
      network: host
      args:
        - CARLA_REPO=${CARLA_REPO:-carlasim/carla}
        - CARLA_TAG=${CARLA_VERSION:-0.9.13}
        - CARLA_VERSION=${CARLA_VERSION:-0.9.13}
    image: carla_ros_bridge:adore
    command: /bin/bash -c "source /opt/carla-ros-bridge/install/setup.bash; source /opt/carla/setup.bash; roslaunch /opt/carla-ros-bridge/launchfiles/carla_rosbridge_with_cybertruck_as_ego_vehicle.launch"
    #command: tail -F anything
    #stdin_open: true 
    #tty: true
    runtime: nvidia
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/tmp/adore_if_carla/
    network_mode: host
    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
  adore_if_carla:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.adore_if_carla
      network: host
      args:
        - PLOTLABLIB_TAG=${PLOTLABLIB_TAG}
        - ADORE_IF_ROS_MSG_TAG=${ADORE_IF_ROS_MSG_TAG}
        - CARLA_REPO=${CARLA_REPO:-carlasim/carla}
        - CARLA_TAG=${CARLA_VERSION:-0.9.13}
    image: adore_if_carla:${ADORE_IF_CARLA_TAG}
    command: /bin/bash -c "source /tmp/adore_if_carla/build/catkin_generated/installspace/setup.bash; roslaunch /tmp/adore_if_carla/launch/demo014_adore_if_carla_part.launch"
    #command: tail -F anything
    #stdin_open: true 
    #tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
