services:
  carla_headless:
    extends: carla_core
    command: /bin/bash ./CarlaUnreal.sh -RenderOffScreen --ros2
  carla:
    extends: carla_core
    command: /bin/bash ./CarlaUnreal.sh --ros2
  carla_core:
    image: carlasim/carla:0.10.0
    container_name: carla
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('localhost', 2000)); s.close()"]
      interval: 5s
      retries: 30
      start_period: 30s
      timeout: 5s
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=./fastrtps-profile.xml
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    #command: /bin/bash ./CarlaUnreal.sh --ros2
    runtime: nvidia
  carla_bridge:
    extends: carla_bridge_core
    command: /bin/bash -c "cd /tmp/carla_bridge; python ros2.py -f stack.json"
    depends_on:
      carla:
        condition: service_healthy
  carla_bridge_headless:
    extends: carla_bridge_core
    command: /bin/bash -c "cd /tmp/carla_bridge; python ros2.py -f stack.json"
    depends_on:
      carla_headless:
        condition: service_healthy
  carla_bridge_core:
    build:
      context: .
      dockerfile: ./Dockerfile.carla_bridge
      network: host
    image: adore_carla_rosbridge:latest
    container_name: carla_ros_bridge
    runtime: nvidia
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/tmp/carla_bridge/
    network_mode: host
    environment:
      - FASTRTPS_DEFAULT_PROFILES_FILE=./fastrtps-profile.xml
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
