find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(adore_ros2_msgs REQUIRED)
find_package(std_msgs REQUIRED)
find_package(ament_lint_auto REQUIRED)
find_package(tf2_ros REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_geometry_msgs REQUIRED)
find_package(adore_dynamics_conversions REQUIRED)
find_package(adore_map_conversions REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(carla_msgs REQUIRED)
list(APPEND CMAKE_MODULE_PATH "/usr/share/cmake/geographiclib/")
find_package(GeographicLib REQUIRED)
set(GeographicLib_TARGETS GeographicLib)