name: Test 
on: push

jobs:
  install_requirements:
    runs-on: ubuntu-latest
    steps:
    - name: Install GNU Make
      run: sudo apt-get update && sudo apt-get -y install make

  ci:
    runs-on: ubuntu-latest
    needs: install_requirements 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Build
        run: make ci_build && make save_docker_images
      - name: Test
        run: make ci_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y make
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 35000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
        run: |
          make build
      - name: Test
        run: |
          make ci_test

